[package]
name = "rhkd"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "0.10.0"
xcb-util = { version = "0.4.0", features = ["keysyms"] }
x11 = "2.19.1"
paste = "1.0.6"
futures = "*"